//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gumblr {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NationalTeamLogoNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NationalTeamLogoNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gumblr.NationalTeamLogoNames", typeof(NationalTeamLogoNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALG.
        /// </summary>
        internal static string Algeria {
            get {
                return ResourceManager.GetString("Algeria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARG.
        /// </summary>
        internal static string Argentina {
            get {
                return ResourceManager.GetString("Argentina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUS.
        /// </summary>
        internal static string Australia {
            get {
                return ResourceManager.GetString("Australia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEL.
        /// </summary>
        internal static string Belgium {
            get {
                return ResourceManager.GetString("Belgium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIH.
        /// </summary>
        internal static string Bosnia_and_Herzegovina {
            get {
                return ResourceManager.GetString("Bosnia_and_Herzegovina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRA.
        /// </summary>
        internal static string Brazil {
            get {
                return ResourceManager.GetString("Brazil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMR.
        /// </summary>
        internal static string Cameroon {
            get {
                return ResourceManager.GetString("Cameroon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHI.
        /// </summary>
        internal static string Chile {
            get {
                return ResourceManager.GetString("Chile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COL.
        /// </summary>
        internal static string Colombia {
            get {
                return ResourceManager.GetString("Colombia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRC.
        /// </summary>
        internal static string Costa_Rica {
            get {
                return ResourceManager.GetString("Costa_Rica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIV.
        /// </summary>
        internal static string Côte_d_Ivoire {
            get {
                return ResourceManager.GetString("Côte_d_Ivoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRO.
        /// </summary>
        internal static string Croatia {
            get {
                return ResourceManager.GetString("Croatia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECU.
        /// </summary>
        internal static string Ecuador {
            get {
                return ResourceManager.GetString("Ecuador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENG.
        /// </summary>
        internal static string England {
            get {
                return ResourceManager.GetString("England", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRA.
        /// </summary>
        internal static string France {
            get {
                return ResourceManager.GetString("France", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GER.
        /// </summary>
        internal static string Germany {
            get {
                return ResourceManager.GetString("Germany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GHA.
        /// </summary>
        internal static string Ghana {
            get {
                return ResourceManager.GetString("Ghana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRE.
        /// </summary>
        internal static string Greece {
            get {
                return ResourceManager.GetString("Greece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HON.
        /// </summary>
        internal static string Honduras {
            get {
                return ResourceManager.GetString("Honduras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRN.
        /// </summary>
        internal static string Iran {
            get {
                return ResourceManager.GetString("Iran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITA.
        /// </summary>
        internal static string Italy {
            get {
                return ResourceManager.GetString("Italy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPN.
        /// </summary>
        internal static string Japan {
            get {
                return ResourceManager.GetString("Japan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KOR.
        /// </summary>
        internal static string Korea_Republic {
            get {
                return ResourceManager.GetString("Korea_Republic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEX.
        /// </summary>
        internal static string Mexico {
            get {
                return ResourceManager.GetString("Mexico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NED.
        /// </summary>
        internal static string Netherlands {
            get {
                return ResourceManager.GetString("Netherlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGA.
        /// </summary>
        internal static string Nigeria {
            get {
                return ResourceManager.GetString("Nigeria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POR.
        /// </summary>
        internal static string Portugal {
            get {
                return ResourceManager.GetString("Portugal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUS.
        /// </summary>
        internal static string Russia {
            get {
                return ResourceManager.GetString("Russia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESP.
        /// </summary>
        internal static string Spain {
            get {
                return ResourceManager.GetString("Spain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUI.
        /// </summary>
        internal static string Switzerland {
            get {
                return ResourceManager.GetString("Switzerland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URU.
        /// </summary>
        internal static string Uruguay {
            get {
                return ResourceManager.GetString("Uruguay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA.
        /// </summary>
        internal static string USA {
            get {
                return ResourceManager.GetString("USA", resourceCulture);
            }
        }
    }
}
